import 'package:flutter/material.dart';
import '../theme.dart';

class SummarizeScreen extends StatefulWidget {
  const SummarizeScreen({Key? key}) : super(key: key);

  @override
  _SummarizeScreenState createState() => _SummarizeScreenState();
}

class _SummarizeScreenState extends State<SummarizeScreen> {
  final TextEditingController _textController = TextEditingController();
  String? _summary;
  bool _isLoading = false;

  @override
  void dispose() {
    _textController.dispose();
    super.dispose();
  }

  void _generateSummary() {
    // Check if text is empty
    if (_textController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter some text to summarize')),
      );
      return;
    }

    setState(() {
      _isLoading = true;
    });

    // Simulate API call delay
    Future.delayed(const Duration(seconds: 1), () {
      setState(() {
        // Mock summary - in a real app, this would come from an API
        _summary = 'This is a summarized version of the text you entered. '
            'In a real application, this would be generated by an AI model based on your input. '
            'The summary would highlight the key points and main ideas from your text, '
            'making it easier to understand and remember the important information.';
        _isLoading = false;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Summarize Text'),
        backgroundColor: AppTheme.summarizeColor,
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            const Text(
              'Enter text to summarize:',
              style: AppTheme.titleLarge,
            ),
            const SizedBox(height: 8),
            TextField(
              controller: _textController,
              maxLines: 6,
              decoration: const InputDecoration(
                hintText: 'Paste your text here...',
                border: OutlineInputBorder(),
              ),
            ),
            const SizedBox(height: 16),
            ElevatedButton(
              onPressed: _isLoading ? null : _generateSummary,
              style: ElevatedButton.styleFrom(
                backgroundColor: AppTheme.summarizeColor,
              ),
              child: _isLoading
                  ? const CircularProgressIndicator(color: Colors.white)
                  : const Text('Generate Summary'),
            ),
            const SizedBox(height: 24),
            if (_summary != null) ...[
              const Text(
                'Summary:',
                style: AppTheme.headlineMedium,
              ),
              const SizedBox(height: 8),
              Expanded(
                child: Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: AppTheme.summarizeColor.withOpacity(0.1),
                    borderRadius: BorderRadius.circular(8),
                    border: Border.all(color: AppTheme.summarizeColor.withOpacity(0.3)),
                  ),
                  child: SingleChildScrollView(
                    child: Text(
                      _summary!,
                      style: AppTheme.bodyLarge,
                    ),
                  ),
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }
}
